# Generated by Django 4.0.6 on 2024-06-10 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='apellido',
            field=models.CharField(default='None', max_length=250),
        ),
        migrations.AddField(
            model_name='user',
            name='dog_1',
            field=models.CharField(default='None', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='dog_2',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='dog_3',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='dog_4',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='dog_5',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='nombre',
            field=models.CharField(default='None', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='rewards',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='telefono',
            field=models.CharField(default='None', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=250, unique=True),
        ),
    ]
