# Generated by Django 4.0.6 on 2024-06-10 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user_apellido_user_dog_1_user_dog_2_user_dog_3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dog_2',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
