# Generated by Django 4.0.6 on 2024-06-10 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_user_dog_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dog_2',
            field=models.CharField(blank=True, default='None', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='dog_3',
            field=models.CharField(default='None', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='dog_4',
            field=models.CharField(default='None', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='dog_5',
            field=models.CharField(default='None', max_length=250, null=True),
        ),
    ]
