# Generated by Django 4.0.6 on 2024-06-11 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_user_dog_2_alter_user_dog_3_alter_user_dog_4_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='dog_1',
        ),
        migrations.RemoveField(
            model_name='user',
            name='dog_2',
        ),
        migrations.RemoveField(
            model_name='user',
            name='dog_3',
        ),
        migrations.RemoveField(
            model_name='user',
            name='dog_4',
        ),
        migrations.RemoveField(
            model_name='user',
            name='dog_5',
        ),
        migrations.CreateModel(
            name='Dogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('raza', models.CharField(max_length=250)),
                ('sexo', models.CharField(choices=[('macho', 'MACHO'), ('hembra', 'HEMBRA')], default='macho', max_length=20)),
                ('propietario', models.ForeignKey(max_length=250, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
