# Generated by Django 4.0.6 on 2024-06-11 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_user_dog_1_remove_user_dog_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogs',
            name='is_special',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dogs',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
