# Generated by Django 4.0.6 on 2024-07-06 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_reserves_daily_fecha_in_reserves_daily_paquete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserves_daily',
            name='paquete',
            field=models.CharField(choices=[('medio', 'Medio dia - $7.49'), ('1dia', 'Pase Diario - $12.84'), ('3dias', 'Pase 3 dias - $35.31'), ('6dias', 'Pase 6 dias - $64.20'), ('12dias', 'Pase 12 dias - $117.70'), ('24dias', 'Pase 24 dias - $214.00')], default='medio', max_length=250),
        ),
    ]
