# Generated by Django 4.0.6 on 2024-07-06 03:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_reserves_daily_paquete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserves_daily',
            name='propietario',
            field=models.ForeignKey(max_length=250, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
