# Generated by Django 5.1.3 on 2025-01-22 03:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_reserves_daily_is_checked_in'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserves_Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_in', models.DateField(default='2024-01-01')),
                ('fecha_out', models.DateField(default='2024-01-01')),
                ('is_checked_in', models.BooleanField(default=False)),
                ('dog', models.ForeignKey(max_length=250, on_delete=django.db.models.deletion.CASCADE, to='main.dogs')),
                ('propietario', models.ForeignKey(max_length=250, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
