# Generated by Django 5.1.3 on 2025-01-31 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_reserves_hotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserves_daily',
            name='paquete',
            field=models.CharField(choices=[('medio', 'Medio dia - $7.49'), ('1', 'Pase Diario - $12.84'), ('3', 'Pase 3 dias - $35.31'), ('6', 'Pase 6 dias - $64.20'), ('12', 'Pase 12 dias - $117.70'), ('24', 'Pase 24 dias - $214.00')], default='medio', max_length=250),
        ),
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
