# Generated by Django 5.1.3 on 2025-02-08 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_dogs_vacunacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telefono',
            field=models.CharField(default='9999-9999', max_length=25),
        ),
    ]
