# Generated by Django 5.1.3 on 2025-02-13 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_user_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserves_daily',
            name='chech_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reserves_daily',
            name='chech_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
