# Generated by Django 5.1.3 on 2025-02-13 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_reserves_daily_chech_in_reserves_daily_chech_out'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserves_daily',
            old_name='chech_in',
            new_name='check_in',
        ),
        migrations.RenameField(
            model_name='reserves_daily',
            old_name='chech_out',
            new_name='check_out',
        ),
    ]
